### ISSUE TITLE
[8.0 alpha]PHP Fatal error:  Uncaught Error: Class "Elastic\\Transport\\TransportBuilder" not found in /src/ClientBuilder.php:315

### ISSUE THREAD

**Issue by chongshengdz** [elastic/elasticsearch-php#1200]
[8.0 alpha]PHP Fatal error:  Uncaught Error: Class "Elastic\\Transport\\TransportBuilder" not found in /src/ClientBuilder.php:315

**Comment by ezimuel** [comment]
@chongshengdz can you try using [v8.0.0-RC1](https://github.com/elastic/elasticsearch-php/releases/tag/v8.0.0-rc1) ? Thanks.

**Comment by chongshengdz** [comment]
Many thanks for the reply.
i will try it later today.

**Comment by ezimuel** [comment]
@chongshengdz I found the issue there was a missing `v`in the require for `elastic-transport-php` in`composer.json`. The correct one should be:
```json
 "elastic/transport": ">=v8.0.0-rc4"
```
I released elastic/transport [8.0.0-rc4](https://github.com/elastic/elastic-transport-php/releases/tag/v8.0.0-rc4) in the meantime and I'm going to release `elsaticsearch-php` `v8.0.0-rc2` with the fix.

**Comment by chongshengdz** [comment]
> @chongshengdz can you try using [v8.0.0-RC1](https://github.com/elastic/elasticsearch-php/releases/tag/v8.0.0-rc1) ? Thanks.

PHP Fatal error: Uncaught Error: Class "Composer\InstalledVersions" not found in /transport/src/Transport.php:439, referer:

**Comment by chongshengdz** [comment]
Connection could not be established.The client noticed that the server is not Elasticsearch and we do not support this unknown product×
Read Timeout

**Comment by ezimuel** [comment]
@chongshengdz I released `elastic-transport-php` [v8.0.0-rc4](https://github.com/elastic/elastic-transport-php/releases/tag/v8.0.0-rc4) and `elasticsearch-php` [v8.0.0-rc2](https://github.com/elastic/elasticsearch-php/releases/tag/v8.0.0-rc2). In order to install these RC versions you need to install `elastic-transport-php` and after `elasticsearch-php` as follows:
```bash
composer require elastic/transport:8.0.0-rc4
composer require elasticsearch/elasticsearch:8.0.0-rc2
```
This will produce the following `composer.json`:
```json
"require": {
    "elastic/transport": "8.0.0-rc4",
    "elasticsearch/elasticsearch": "8.0.0-rc2"
}
```
Regarding the error message `The client noticed that the server is not Elasticsearch and we do not support this unknown product` this means you are using a previous 7.x version of Elasticsearch server or a not supported product. Starting from version 8 the `elasticsearch-php` client supports only Elasticsearch 8+ server.

**Comment by chongshengdz** [comment]
> ```shell
> composer require elasticsearch/elasticsearch:8.0.0-rc2
> ```

I did follow your above instruction.
but the error still persist.
PHP Fatal error:  Uncaught Error: Class "Composer\\InstalledVersions" not found in /vendor/elastic/transport/src/Transport.php:439
I am using elasticsearch version 8.1.0
elasticsearch-php v8.0.0-rc2
elastic-transport-php v8.0.0-rc4
php 8.0+


$this->client = \Elastic\Elasticsearch\ClientBuilder::create()->setHosts($host)->build();
 is it correct?

**Comment by chongshengdz** [comment]
Composer version 1.10.22 2021-04-27 13:10:45
centos 7

**Comment by chongshengdz** [comment]
it works fine after upgrading to Composer 2.0+.
the problem is due to i was using an old version of 1.0+.
"Composer\InstalledVersions" is only available on Composer 2.0+.
