### ISSUE TITLE
Elasticsearch 5.5.2 : NoNodesAvailableException

### ISSUE THREAD

**Issue by chandni21** [elastic/elasticsearch-php#648]
I am newbie in Elasticsearch. I am trying to set up elasticsearch with laravel and db. I am getting NoNodesAvailableException error while executing below code. 

Error 

> : NoNodesAvailableException in SniffingConnectionPool.php line 50:
> No alive nodes found in your cluster

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Elasticsearch\ClientBuilder;
use Elastica\Client as ElasticaClient;

class clientController extends Controller
{
    protected $elasticsearch;
    protected $elastica;
    public function __construct()
    {
        $this->elasticsearch = ClientBuilder::create()
				 ->setHosts(['http://localhost:9200'])
				 ->setRetries(100)								
			    ->setConnectionPool('\Elasticsearch\ConnectionPool\SniffingConnectionPool', [])
                ->build();
    }
    public function elasticsearchTest(){       
        $param = [
            'index' => 'property',
            'type' => 'applaince',
            'id'=>'1'
        ];
        $res = $this->elasticsearch->get($param);
        dump($res); 
     /*   try { 
            $res = $this->elasticsearch->get($param);
          } catch (\Exception $e) {
            var_dump($this->elasticsearch->transport->getLastConnection()->getLastRequestInfo());
          }*/
    }
}
```

In above code if I enable  var_dump($this->elasticsearch->transport->getLastConnection()->getLastRequestInfo()); then throw below error.

> FatalThrowableError in clientController.php line 42:
> Call to a member function getLastRequestInfo() on null

Elasticsearch log:

> [2017-09-14T14:03:23,987][INFO ][o.e.n.Node               ] [elastic_client] initialized
> [2017-09-14T14:03:23,987][INFO ][o.e.n.Node               ] [elastic_client] starting ...
> [2017-09-14T14:03:24,767][INFO ][o.e.t.TransportService   ] [elastic_client] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
> [2017-09-14T14:03:24,798][WARN ][o.e.b.BootstrapChecks    ] [elastic_client] initial heap size [268435456] not equal to maximum heap size [536870912]; this can cause resize pauses and prevents mlockall from locking the entire heap
> [2017-09-14T14:03:28,032][INFO ][o.e.c.s.ClusterService   ] [elastic_client] new_master {elastic_client}{Zb8_oEyzQVWCHAS49T0O8Q}{YmMYyeLYSGWtJY2ygm_eig}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
> [2017-09-14T14:03:28,598][INFO ][o.e.g.GatewayService     ] [elastic_client] recovered [2] indices into cluster_state
> [2017-09-14T14:03:28,630][INFO ][o.e.h.n.Netty4HttpServerTransport] [elastic_client] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
> [2017-09-14T14:03:28,631][INFO ][o.e.n.Node               ] [elastic_client] started
> [2017-09-14T14:03:30,391][INFO ][o.e.c.r.a.AllocationService] [elastic_client] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[property][3], [property][2]] ...]).

- Operating System - Win 7 64 Bit
- PHP Version - 7.0
- Elasticsearch version - 5..5.2

**Comment by polyfractal** [comment]
I believe this is related to #629.  I need to do a few other things on the client today, so I'll push a fix and tag it soon.

**Comment by chandni21** [comment]
Thanks for checking this. 
I just enabled logs and  found below cURL error.

> cURL error 7: Failed to connect to localhost port 1080: Connection refused

Logs:

> 2017-09-15 15:20:42] log.WARNING: Curl exception encountered. [] []
> [2017-09-15 15:20:42] log.WARNING: Request Failure: {"method":"GET","uri":"http://localhost:9200/pets/dog/1","headers":{"host":["localhost:9200"],"Content-type":["application/json"],"Accept":["application/json"]},"HTTP code":null,"duration":0.453,"error":"cURL error 7: Failed to connect to localhost port 1080: Connection refused"} []
> [2017-09-15 15:20:42] log.WARNING: Response [null] []
> [2017-09-15 15:20:42] log.WARNING: Marking node localhost:9200 dead. [] []
> [2017-09-15 15:20:42] log.WARNING: Retries left? false [] []
> [2017-09-15 15:20:42] log.WARNING: Out of retries, throwing exception from localhost:9200 [] []
>

**Comment by polyfractal** [comment]
Hm, why is port 1080 being used?  Do you have some kind of proxy locally, or a container like docker?

You could try Elasticsearch-php `dev-master` and see if that fixes things.  I fixed the sniffing code but haven't tagged a release yet, but it should be available in dev-master

**Comment by chandni21** [comment]
Thanks for checking this.

Will try it .
Yes docker was installed but then I uninstalled it but still don't know why
or which application use it.

**Comment by polyfractal** [comment]
I'm not sure, but I suspect Docker may have fiddled with your networking config/settings.  I'd do an audit of the networking settings to make sure there isn't a virtual bridge or something that is configured.  I'm not too familiar with how docker or windows networking works though, so I'm not sure I can be much help :(

In either case, the client definitely shouldn't be talking to port 1080 when the url says 9200 :)  So whatever is causing that is likely the root cause

**Comment by polyfractal** [comment]
I'm not sure, but I suspect Docker may have fiddled with your networking config/settings.  I'd do an audit of the networking settings to make sure there isn't a virtual bridge or something that is configured.  I'm not too familiar with how docker or windows networking works though, so I'm not sure I can be much help :(

In either case, the client definitely shouldn't be talking to port 1080 when the url says 9200 :)  So whatever is causing that is likely the root cause

**Comment by chandni21** [comment]
Thanks.
But I am not sure whether I am already using this elasticsearch - PHP or not. All I know , I have configured th eelastic search with PHP as mentioned here - https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_installation_2.html

**Comment by mcn-fredw** [comment]
Seeing this issue in v5.3.2.
ElastaticSearch server is AWS ElasticSearch service running version 5.5.
Same code is working with AWS ElsticSearch service version 5.3.
The Admin tells me the AWS policy for both of the 5.3 and 5.5 services are identical.
aws sdk version: 3.45.3
jsq/amazon-es-php version: 0.2.1

Testing from command line (curl GET) on same host using aws proxy to sign the request shows the server is reachable.
Testing on an internal host (allowed to do anonymous requests) shows the HEAD request is returning the expected 404 response (the alias does not exist).

The host names are of the form: "https://aws-host-name:443"

Our initialisation code looks like:
    public function getClient()
    {
        if (is_null(static::$client)) {
            $builder = ClientBuilder::create();

            if (! DEVELOPMENT_MACHINE && ! TRAVIS_ENVIRONMENT) {
                $builder->setHandler(new ElasticsearchPhpHandler('us-west-2'));
            }

            // AWS_ES_HOST is a string of the form https://host-name:443
            static::$client = $builder->setHosts([AWS_ES_HOST])->build();
        }

        return static::$client;
    }

AWS does not provide a way to access the raw ElasticSearch request logs.

Symptom is the webpage request takes a long time to complete, then returns the following partial stack trace:
Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51
Stack trace: #0 source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(72): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection()
#1 source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(90): Elasticsearch\Transport->getConnection()
#2 source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(240): Elasticsearch\Transport->performRequest('HEAD', '/_alias/myalias', Array, NULL, Array)
#3 source/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}

**Comment by polyfractal** [comment]
> Testing from command line (curl GET) on same host using aws proxy to sign the request shows the server is reachable.

I'm sorry, I think this is out of the scope of troubleshooting on the client.  It sounds like there is a larger issue with your AWS setup since the curl command isn't working either.

I'm going to close this issue as the original problem (related to sniffing) was fixed in d7716991a7d1a50c38e3fc2bb8582402e6e1d52f and tagged in `v5.3.2`.  Other problems should be raised in a new ticket.

**Comment by mcn-fredw** [comment]
The curl command is working, but I agree that it's more likely an issue
with our AWS setup. Asked our admin to open a AWS support ticket.

**Comment by polyfractal** [comment]
:+1: If you think it's something about the client, feel free to open a new ticket so we can work on it there :)

**Comment by masterzen** [comment]
@mcn-fredw I just encountered the exact same issue on AWS when we upgraded our AWS ES to 5.5.

This is fixed with the latest `amazon-es-php` version, see https://github.com/jeskew/amazon-es-php/pull/10 for more information.
